# Generated by Django 5.0.2 on 2024-03-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='experience',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='photos',
            field=models.FileField(null=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='contact',
            name='projects',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='resume',
            field=models.FileField(null=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
